start chrome "http://www.google.com/trends/trendsReport?hl=en-US&q=Automotive Industry,Donald+Trump&tz=Etc%2FGMT%2B7&content=1&export=1"
start chrome "http://www.google.com/trends/trendsReport?hl=en-US&q=Classic Vehicles,Donald+Trump&tz=Etc%2FGMT%2B7&content=1&export=1"
start chrome "http://www.google.com/trends/trendsReport?hl=en-US&q=Hybrid & Alternative Vehicles,Donald+Trump&tz=Etc%2FGMT%2B7&content=1&export=1"
start chrome "http://www.google.com/trends/trendsReport?hl=en-US&q=Trucks & SUVs,Donald+Trump&tz=Etc%2FGMT%2B7&content=1&export=1"
start chrome "http://www.google.com/trends/trendsReport?hl=en-US&q=Vehicle Maintenance,Donald+Trump&tz=Etc%2FGMT%2B7&content=1&export=1"
start chrome "http://www.google.com/trends/trendsReport?hl=en-US&q=Vehicle Shows,Donald+Trump&tz=Etc%2FGMT%2B7&content=1&export=1"
start chrome "http://www.google.com/trends/trendsReport?hl=en-US&q=Off-Road Vehicles,Donald+Trump&tz=Etc%2FGMT%2B7&content=1&export=1"
start chrome "http://www.google.com/trends/trendsReport?hl=en-US&q=Bicycles & Accessories,Donald+Trump&tz=Etc%2FGMT%2B7&content=1&export=1"
start chrome "http://www.google.com/trends/trendsReport?hl=en-US&q=Boats & Watercraft,Donald+Trump&tz=Etc%2FGMT%2B7&content=1&export=1"
start chrome "http://www.google.com/trends/trendsReport?hl=en-US&q=Campers & RVs,Donald+Trump&tz=Etc%2FGMT%2B7&content=1&export=1"
start chrome "http://www.google.com/trends/trendsReport?hl=en-US&q=Commercial Vehicles,Donald+Trump&tz=Etc%2FGMT%2B7&content=1&export=1"
start chrome "http://www.google.com/trends/trendsReport?hl=en-US&q=Cargo Trucks & Trailers,Donald+Trump&tz=Etc%2FGMT%2B7&content=1&export=1"
start chrome "http://www.google.com/trends/trendsReport?hl=en-US&q=Custom & Performance Vehicles,Donald+Trump&tz=Etc%2FGMT%2B7&content=1&export=1"
start chrome "http://www.google.com/trends/trendsReport?hl=en-US&q=Electric & Plug-In Vehicles,Donald+Trump&tz=Etc%2FGMT%2B7&content=1&export=1"
start chrome "http://www.google.com/trends/trendsReport?hl=en-US&q=Microcars & City Cars,Donald+Trump&tz=Etc%2FGMT%2B7&content=1&export=1"
start chrome "http://www.google.com/trends/trendsReport?hl=en-US&q=Motorcycles,Donald+Trump&tz=Etc%2FGMT%2B7&content=1&export=1"
start chrome "http://www.google.com/trends/trendsReport?hl=en-US&q=Personal Aircraft,Donald+Trump&tz=Etc%2FGMT%2B7&content=1&export=1"
start chrome "http://www.google.com/trends/trendsReport?hl=en-US&q=Scooters & Mopeds,Donald+Trump&tz=Etc%2FGMT%2B7&content=1&export=1"
start chrome "http://www.google.com/trends/trendsReport?hl=en-US&q=SUVs,Donald+Trump&tz=Etc%2FGMT%2B7&content=1&export=1"
